version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    env_file:
      #- .flaskenv
      - .env
    ports:
      - '5000:5000'
    

  redis:
    image: redis
    container_name: redis-container-cache
    ports:
      - "6379:6379"
    volumes:
      - ./cache-data:/var/lib/redis/cache/data